name: Kubernetes Deploy

on:
  workflow_dispatch:

env:
  IMAGE_NAME: tanayjain29/flask-devops-app

jobs:

  build-push:

    runs-on: ubuntu-latest

    outputs:
      image-tag: ${{ github.sha }}

    steps:

      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest

  deploy-kubernetes:

    needs: build-push

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Replace Image Placeholder
        run: |
          sed -i \
          "s|IMAGE_TAG_PLACEHOLDER|${{ env.IMAGE_NAME }}:${{ github.sha }}|g" \
          k8s/deployment.yaml

      - name: Production Deploy Example
        run: |
          echo "kubectl apply -f k8s/"
          echo "kubectl rollout status deployment/flask-app"
          echo "Image deployed:"
          echo "${{ env.IMAGE_NAME }}:${{ github.sha }}"
